spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    username: "root"
    password: "GWKBPvCiBNwpTw"
    url: jdbc:mysql://107.174.196.241:3306/mydb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/root/light/

server:
  port: 80