spring:
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    username: "root"
    password: "---"
    url: jdbc:mysql://---/mydb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/root/light/

server:
  port: 80